# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# This workflow will also lint java progs against defined coding style in checkstyle.xml

name: Maven Build

on:
  workflow_call:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml -DskipTests
  
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      # Checkout the calling repository
      - name: Checkout current repo
        uses: actions/checkout@v3

      # Checkout the central config repo
      - name: Checkout central config repo
        uses: actions/checkout@v4
        with:
          repository: mdegi/gitCentralConfig
          path: central-config
          token: ${{ secrets.GITHUB_TOKEN }}
          # Full git history is needed to get a proper list of changed files
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v6
        env:
          LINTER_RULES_PATH: central-config/.github/linters/
          JAVA_FILE_NAME: checkstyle.xml
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JAVA: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
